name = "testing"
uuid = "fa4ab20a-8029-470a-9410-a6170bc4368e"
authors = ["Kristoffer Carlsson <kristoffer.carlsson@juliacomputing.com>"]
version = "0.1.0"


[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

